name: Build/Publish

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:

env:
  COMPONENT: stock-cloudfunctions
  GOOGLE_PROJECT: sknups-org-admin
  BUILD_ARTIFACTS_BUCKET: build-artifacts-09c4

jobs:
  build-publish:
    name: Build/Publish
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Auth GCP   
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.BUILD_ARTIFACTS_BUCKET_ADMIN }}'

      - name: Setup GCP      
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.GOOGLE_PROJECT }}

      - name: Setup Node    
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure npm
        run: |
          npm config set update-notifier false
          npm config set audit false
          npm config set fund false

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm test
  
      - name: Build
        run: |
          npm run build

      - name: Package
        run: |-          
          mkdir build
          cp -a ./dist ./build
          cp package*.json ./build
          cd build
          zip -r "../$GITHUB_SHA.zip" .

      - name: Upload
        if: github.event_name != 'pull_request'
        run: |-
          gsutil cp "$GITHUB_SHA.zip" "gs://$BUILD_ARTIFACTS_BUCKET/$COMPONENT/$GITHUB_SHA.zip"

      - name: Deploy
        if: github.event_name == 'push'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update_version.yml
          repo: sknups/wholesale-terraform
          token:  ${{ secrets.DEPLOY_TOKEN }}
          inputs: '{ "component": "${{ env.COMPONENT }}", "version": "${{ github.sha }}" }'